global:
  resolve_timeout: 10s

route:
  group_by: ['alertname']
  group_wait: 3s
  receiver: ['telegram_bot','email']

receivers:
- name: 'telegram_bot'
  telegram_configs:
  - bot_token: 'YOUR_TOKEN_HERE'
    api_url: 'https://api.telegram.org'
    chat_id: YOUR_CHAT_ID
    parse_mode: 'HTML'

- name: 'email'
  email_configs:
  - to: 'recipient@gmail.com'
    from: 'email_id@gmail.com'
    smarthost: smtp.gmail.com:587
    auth_username: 'email_id@gmail.com'
    auth_identity: 'email_id@gmail.com'
    auth_password: 'password'
