global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'monitoring-top'
    server_name: prometheus-test # Имя сервера для отображения в VM

# Метрики в викторию
remote_write:
  - url: http://192.168.56.106:8428/api/v1/write
    queue_config:
      max_samples_per_send: 10000
      capacity: 20000
      max_shards: 30
# Задачи сбора метрик
scrape_configs:
  - job_name: exporter
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: cms-exporter
    scrape_interval: 5s
    static_configs:
    - targets: ['192.168.56.104:9100']
 
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://192.168.56.104
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
# Правило отправки алертов
rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"
